### ISSUE TITLE
Console Only Operation

### ISSUE THREAD

**Issue by techno156** [MattJeanes/TARDIS#1058]
**Description:** This would be an alternative way to spawn and operate a TARDIS that doesn't have the police box, either for fun/RP reasons, or in maps/servers where there isn't the space to spawn a TARDIS, but you want some of the functions of the TARDIS that aren't available in its police-box only mode, like co-ordinate/destination setting. 

**Implementation:** This could take the form of an alternate entity that is spawned, that is just the TARDIS console, similar to the bare TARDIS console in ["Inferno"](https://youtu.be/7oE2IXxQBiA) and ["The Doctor's Wife"](https://www.youtube.com/watch?v=2rfOs8sGHi8). 

**Problems with Implementation:** One issue with this would be teleporting the players, as the console would have to take the players along with them, rather than having them in a static skybox console room, where the door-portal effectively moves around instead. This could potentially be resolved by having a "floor" that the console sits on, where anything on the platform is teleported along with the console.

Manual flight mode would be an issue, since unlike with the regular TARDIS, the player model would have to be moved along with the console when it is flown in that state, rather than sitting in the skybox, like it would be in the console room. Possibly doable by reusing the existing manual flight code, if a console cannot be spawned.

**Optional:** The console-only variant might not have any shields, because it has no barriers to protect the console or the occupants.

**Comment by AmyJeanes** [comment]
You may not know this but you can pop the virtual screen up and access pretty much every feature while in exterior only mode by pressing middle mouse (by default) or holding C and clicking on the TARDIS icon.

A unboxed interior e.g. Doctor's Wife is extremely difficult due to the lack of a clear doorway to place a portal. It is possible to have an exterior only TARDIS extension which is just an interior so to speak but you'd end up flying out of it easily and the flight physics / teleporting wouldn't work properly. Maybe could be combined with the [gravity hull designator addon](https://steamcommunity.com/sharedfiles/filedetails/?id=531849338) if that still works to solve some of these problems.

The best thing I can think of is to just use the virtual menu, but failing that use/create a TARDIS extension with an extremely small interior footprint, like Bill + Teds that should be able to spawn on any map.

I'm going to close this as the feature as you describe can't really be improved more beyond what I have suggested above which is not something we will do in the core TARDIS addon.

That said, I do really appreciate the clear issue description, it's one of the best I have ever seen so thank you!
