### ISSUE TITLE
A Hook Consumes 5 to 6 ms Per Second of Compute Time When Not Having Any TARDIS Spawned

### ISSUE THREAD

**Issue by Wormsweat** [MattJeanes/TARDIS#1084]
When all addons are disabled except for TARDIS, Doors, Time Vortex Pack, [PERFOPUS: Performance Metrics](https://steamcommunity.com/sharedfiles/filedetails/?id=3367512048), and the library the performance metrics requires, the hook called tardis-aprilfools consumes 5 to 6 ms of compute per second when it's not April Fools Day and when no TARDIS is spawned. Does it for some reason have to be this way or is it oversight?
![20241129190826_1](https://github.com/user-attachments/assets/76299a1b-3dda-4e0c-a1aa-3ec868112224)

**Comment by AmyJeanes** [comment]
This is fixed in [2024.2.2](https://github.com/MattJeanes/TARDIS/releases/tag/2024.2.2)

It does still have a minor impact due to the nature of the `PostDrawTranslucentRenderables` hook but it should be much improved.

Didn't know about that performance metrics addon, that's super useful! If you see any other weird unusually high performance hits please let me know.

Appreciate the report, thank you!

**Comment by AmyJeanes** [comment]
Also just to note, it was the `os.date` call that was causing most of the perf hit
