### ISSUE TITLE
Conditions and Actions

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#113]
There could be a menu in which you could set conditions and actions, for example if tardis health is below 20%, teleport to certain coordinates or something. Not 100% about this, but it's a nice idea

**Comment by Noname12345GER** [comment]
You mean like the Android App "Tasker" ?
Would fit in Programmable Flightmode :]
But should be able to detect props for certain actions like shown here:

https://youtu.be/ByPrDPbdRhc?t=2m10s

**Comment by MattJeanes** [comment]
Yeah sorta like that

**Comment by TheDetecttive** [comment]
Well, if you do end up adding this, it'd be great to have the ability to be notified when this happens, I can just imagine someone being away from their TARDIS for some time, one of their conditions being met, the TARDIS flying away, them returning, and it's gone, especially if you were running away from another player or a mob of hostile enemies, it'd be useful to know where your TARDIS is. Also, this could help in having a "key" you could make it so if you make some prop a TARDIS key, other people not on your whitelist could enter. (Though it would be helpful to make one specific prop a key, rather than all props of the same type a key. For example, I want to make a soda can the TARDIS "key", but I do not want all soda cans to be a TARDIS key, I just want this one soda can to be a TARDIS key.) Also! It could be fun to have custom names, so if there are notifications, it could say "Protocol Ten has been activated." or you could make it really anything you want it to be, Hazardous Action Displacement System with specified landing area or anything really.

**Comment by parar020100** [comment]
Isn't this possible with wiremod and E2?
If yes, I think there's no need to do more
If not, perhaps do something like that with E2?

I don't think the addon is used so much that it is worth creating a special system to write algorythms in, even if it's simple

**Comment by MattJeanes** [comment]
Yeah with E2 support now implemented that basically covers this off, we could add features to the E2 system if needed to make certain scenarios possible but should be pretty good already. I'll close this.
