### ISSUE TITLE
Stop guns from being fired in interior

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#146]
Some sort of 'passive mode' or 'temporal grace' as someone put it - probably a term from the show.

Would stop all guns from being fired while it's on. May be issue for source engine weapons but should be OK, fallback is available to stop actually bullets being fired anyway.

**Comment by FailingGravity** [comment]
Could [this](https://wiki.garrysmod.com/page/Player/RemoveAmmo) be used at all?

It would remove ammo, but maybe some ammo could be added back?

**Comment by MattJeanes** [comment]
Maybe if nothing else works

**Comment by Unimagnuss** [comment]
I remember that HL2  when you enter the citadel was similar effect. As well as guys from Carter Addon Pack made similar device (Tollan Weapon Diabler STool)->
Might be worth asking them.

Disables your weapons so that any offensive weapon cannot be used, when you try to get a weapon, it will go back to the physgun. Doesn’t work on NPC’s, more for use in multiplayer.

**Comment by Noname12345GER** [comment]
The doctor said it was a "clever lie"  that weapons cant be fired inside? In "In the parting of ways" a dalek was able to fire his weapon inside the tardis aswell as jack who killed it moments later.

**Comment by MattJeanes** [comment]
Related to #165

**Comment by parar020100** [comment]
tbh, I don't think this is a good idea

**Comment by MattJeanes** [comment]
I don't think this is worth bothering with now so going to close
