### ISSUE TITLE
Rotating in floatmode acts unintended

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#220]
If you go on float and attempt to turn the TARDIS by Holding alt, it doesn't turn on z axis only. I think it's because not all Keys are disabled while Holding alt.

**Comment by MattJeanes** [comment]
Do you mean that you can still go forwards backwards up and down? Only left and right (A and D) keys have modified behaviour when holding alt

**Comment by Noname12345GER** [comment]
In Legacy, you would be able to turn along the z axis in flightmode.

If you press a and d in float, it would rotate around the axis facing to you.

If you press a and d while Holding alt, the above action is combined with z axis turning.

I don't know if it's intended, but kinda doesn't feel right.

**Comment by MattJeanes** [comment]
What do you mean by the Z axis in this context

**Comment by Noname12345GER** [comment]
The vertical axis from the top light to the bottom

**Comment by Noname12345GER** [comment]
In regular flight, the TARDIS will Spin on z-axis.

**Comment by MattJeanes** [comment]
Okay I think I see what you mean now, if what I think you're trying to describe is happening then no that is not intentional. I'll have a look in-game to see when I can.

**Comment by Noname12345GER** [comment]
Have you discovered it?

**Comment by MattJeanes** [comment]
> I'll have a look in-game to see when I can.

**Comment by thehornydragon** [comment]
It seems that when the TARDIS is inside the Vortex, it does rotate the way it should when holding Alt and being in float-mode. However, in the Vortex there is another problem; whether you push A to rotate left, or D to rotate right, you always rotate to the left. Here's a video, since Noname12345GER seems to provide an insufficient amount of information. Video recorded with Windows 10's built-in recorder, so it isn't top-notch quality. [https://www.youtube.com/watch?v=Z-xnudUxCUs](url)

**Comment by MattJeanes** [comment]
Fixed alt rotation in vortex
