### ISSUE TITLE
Relative gravity inside Tardis

### ISSUE THREAD

**Issue by Mysterypancake1** [MattJeanes/TARDIS#277]
Sorry to bother you again, but this is another suggestion I was thinking of.
Would it be possible to have entities in the Tardis move as if they're actually IN the Tardis?
For example, if the Tardis slammed into a wall then they would all fly around, or if the Tardis was upside down the gravity would be as well?

This is probably very tricky to do (especially with the gravity only affecting a certain area) and would get annoying pretty fast, but it'd make the Tardis more realistic.

**Comment by theangelcastiel** [comment]
This is not what actually happens in the show. You can see this with "Flatline" S8 or S9 where Capaldi moves the TARDIS on it's side and he still is standing correctly.

**Comment by Mysterypancake1** [comment]
If not gravity, then don't things shake around in the Tardis quite frequently? I'm not a massive Doctor Who fan, but I can remember lots of times I've seen things shaking a lot

**Comment by theangelcastiel** [comment]
Yes and I would actually like that, more shaking scaling by how far you are traveling. But if that's something you want, raise a sepetate issue.

**Comment by Noname12345GER** [comment]
Let's day if the gravity stabilizers are of it can happen. Like they will disable after the TARDIS is damaged enough. To affect only Props within interior, you can call a function called 

ents.FindInSphere()

This will give you a table of all entities found.

Then you could Call a for Loop where you Loop around on all entities found in the interior.

ENT:ApplyForce( ENT:GetMass*Exterior.GetAngles().pitch, ENT:GetMass*Exterior.GetAngles().yaw, 0 )

This will apply forces proportional to the angle how the TARDIS stands. Probaply you will have to disable gravity on the object because you are making your own concept of gravity.
