### ISSUE TITLE
Programmable Flightmode

### ISSUE THREAD

**Issue by AlexerZoderia** [MattJeanes/TARDIS#283]
I liked the previous TARDIS' ability to save locations on maps to later teleport to, and I'm hoping thats implimented soon, but I would like to see something added onto it like a random code that resembles galactic coordanates, and an option to share those coordinates with other users. As an example, lets say this: You're on Sb_galaxies, your friend is on the desert planet in the universe section of the map, and he gives you his coordinates. This tells the TARDIS where to land, and it will set itself down nearby those coordinates.

**Comment by LoganDark** [comment]
I'd assume the teleporting "near" coordinates would happen once he implements an algorithm for deciding where it's safe for the TARDIS to land.

**Comment by AlienGamer10** [comment]
I believe the Legacy TARDIS had actual coordinates when it came to saving destinations so that way you can change one part and rotate your TARDIS without having to do it manually in flightmode, for one use anyways. So when saved destinations returns, that should most likely be included though I do agree with being able to share them and other data to other TARDISes.

**Comment by Noname12345GER** [comment]
I think it's important to be able to Bypass all algorythms if you need to. 

Im not saying Matt doesn't put effort in it, but I had to rewrite the Version on one of my Servers to use pre-defined Locations for spawning the interior.

**Comment by MattJeanes** [comment]
Pretty much fixed in #312
