### ISSUE TITLE
The problem with the reflections.

### ISSUE THREAD

**Issue by AntohaKapitoha** [MattJeanes/TARDIS#340]
https://steamcommunity.com/sharedfiles/filedetails/?id=2275079007
What to do? Sometimes the inscription above the door stops being black and seems to reflect the gray sky. So with all TARDIS except the standard one.

**Comment by Win7yes** [comment]
This seems to be due to certain (most) maps not having HDR cubemaps built and the engine treating default data wrong, plus poorly tweaked material parameters. 
Unfortunately it's not something we can fix. Only the developers of the extensions you are using can, by tweaking or removing the reflective properties of materials.
A workaround is to disable HDR and restarting the game, or disabling specular reflections. The first one can be done through game settings, and the second through console commands (mat_specular 0 iirc)
