### ISSUE TITLE
Fuel system (Artron energy)

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#42]
Cookiemorph's E2 had something like this. Not sure if I want to do something officially for it.

**Comment by SingularMix** [comment]
I personally would hate to run on a fuel system where you have a certain amount of fuel and when you run out you have to actually get sommething to fill it up. What if instead of a fuel system you did a 'cool down system' where you have this much power before you need to stop and take a pit stop to cool off, then in 20 seconds youre ready to go.

**Comment by logoster** [comment]
well, in the 9th-10th doctor seasons, they had slow radiation leakage for fuel which is refuelled by a rift in time and space in cardiff

or something like that

**Comment by NightOps007** [comment]
If a fuel system is implemented, you might consider adding tardis cable interfaces that will convert artron (tardis power) into rf/eu/etc. Keep the slow passive recharge intact, because the tardis is traditionally powered by the temporal energies of our universe. Just remember that if the tardis should ever completely run out of artron, it will die for good. If in doubt, make it configurable.

**Comment by iNoPeRaTiVe** [comment]
You could possibly have a hatch that opens up and you could scrap props for artron energy. Depending on the size, that's how much artron it gives you.

**Comment by MattJeanes** [comment]
Some decent ideas, still not sure if I want a fuel system at all though yet. We'll see.

**Comment by FailingGravity** [comment]
Maybe this could tie into a hardcore TARDIS mode?

**Comment by Noname12345GER** [comment]
There are consequences if you don't Refill in time:

If TARDIS is out of fuel, it will get the slow, broken Time Rotor Sound Loop on flight with slowed flashing exterior lamp and 1/3 of the original speed.
Teleportation will take significally longer.
Interior lights will Flicker.

Or:

You will hear a specific Sound that the fuel is empty. (I don't remember the name, but it was a humming Sound with would lose on Pitch in an "out of power" fashion)
You will have to "bring" fuel to the TARDIS like in the episodes where the doctor first met the master.

The doctor had a little Crystal with he inserted into the TARDIS to Spark it on again.

Im out of ideas about the mechanics right now. I'll might add some later on.

**Comment by Noname12345GER** [comment]
What about adding it, but disabled by default?

**Comment by parar020100** [comment]
I don't think this is going to work
There has to be a plot or an aim for it to work; also, some restrictions on travelling
In sandbox, where you can respawn the TARDIS (entitiy), it would be practically useless

I suggest this to be closed, though it might be worth looking into if someone makes a detailed suggestion on how it could work (not just "fuel")

**Comment by MattJeanes** [comment]
I think the health system largely makes up for this as it would act much the same, so going to close this.

**Comment by parar020100** [comment]
Since artron energy is being worked on, I have to reopen this
