### ISSUE TITLE
Scanner on large screens (example: 1983) is broken

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#425]
Most likely, it has something to do with screen resolution changes

**Comment by MattJeanes** [comment]
I find that this happens most during lua hot reloads but it's not consistent, often if you respawn it it fixes it. My working theory is that it is caused by the counter used by `GetRenderTarget` in `cl_scanner.lua` resetting during a lua hot reload, and re-using previously used ids and their associated screen sizes. Perhaps it needs to persist via hot reload by making it a global (TARDIS.ScannerID maybe) or just use some other unique identifier.

**Comment by AmyJeanes** [comment]
This might be fixed now as of https://github.com/MattJeanes/TARDIS/commit/993fdb48d84454472227c04fef87b8cbea6bd975

See if you can repro and if not close this

**Comment by parar020100** [comment]
As discussed with @MattJeanes, this should have been solved
