### ISSUE TITLE
Interiors can't have more than 2 additional lights

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#457]
This has been discussed before.
I know that lighting override doesn't allow that, but it also happens even **without** lighting override. 

We need to either find a way to fix this, or find the reason.

**Comment by MattJeanes** [comment]
As I wrote on Discord this appears to be a fundamental issue with source engine lighting in that only a certain number of lights are able to light a model simultaneously. Within the context of the TARDIS interior, this limit is 3 dynamic lights (I imagine the limit is 4 but the world counts as one light). Typically, there is the main light and secondary light (that stays on with no power). This leaves room for one more dynamic light without things starting to break.

Adding more lights results in the source engine prioritising lighting that is closest to the model origin, which in the case of the TARDIS interior prop is usually in the middle. It will pick the 3 closest light sources and any further away just won't work, but they may light props that are closer to the new light source or the players weapons etc.

Therefore I have to close this as wontfix because we cannot fix this, as I understand this limit actually exists in source 2 as well, can't find it right now but in the Half Life: Alyx developer commentary they stated something about a similar limit for maximum dynamic lighting lighting a single object.

https://user-images.githubusercontent.com/2363642/112571735-9102c280-8de0-11eb-8d31-b9e68a4420d5.mp4
