### ISSUE TITLE
Any way to make it so tardis is removed when they change job

### ISSUE THREAD

**Issue by KyberNetworks** [MattJeanes/TARDIS#599]
Any way to make it so tardis is removed when they change job ?

**Comment by AmyJeanes** [comment]
What?

**Comment by KyberNetworks** [comment]
Well  i am having trouble as when people are the timelord job or the doctor or the master they spawn a tardis then when they change job the tardis is still there when it should delete it i have removeclassitems - Enable/disable shipments/microwaves/etc. removal when someone changes team enabled

**Comment by parar020100** [comment]
What's a job?
Is "jobs" something that is added by some other addon?
Please, elaborate

**Comment by KyberNetworks** [comment]
Talking about dakrp jobs

**Comment by AmyJeanes** [comment]
Yes but this is something you'll need to handle in your own code. I don't know much about DarkRP but if you can give a list of classes to clean up try `gmod_tardis`. Otherwise you'll need to write custom Lua code and likely use the `EntityRemoved` hook to see when a TARDIS has been removed. Closing as this is unrelated to the TARDIS addon itself.
